### ISSUE TITLE
Problem with bouncing ball example

### ISSUE THREAD

**Issue by narr95** [simupy/simupy#18]
Hello, I have encountered a error with the execution of bouncing_ball.py. I don't know if it is my fault in the installation of SimuPy or if it's a problem of the code. I'm using Python 3.8, the lastest versions of NumPy, SciPy and SymPy. Moreover, I'm using the development version of SimuPy. Here is the traceback, I hope that it can clarify better the problem:
Traceback (most recent call last):
  File "C:/Users/nicol/PycharmProjects/tesi2/simupy/examples/bouncing_ball.py", line 34, in <module>
    sys = SwitchedSystem(
  File "C:\Users\nicol\PycharmProjects\tesi2\simupy\simupy\discontinuities.py", line 78, in __init__
    DiscontinuousSystem.__init__(self, **kwargs)
  File "C:\Users\nicol\PycharmProjects\tesi2\simupy\simupy\systems\symbolic.py", line 70, in __init__
    self.state_equation = state_equation
  File "C:\Users\nicol\PycharmProjects\tesi2\simupy\simupy\systems\symbolic.py", line 123, in state_equation
    self.update_state_equation_function()
  File "C:\Users\nicol\PycharmProjects\tesi2\simupy\simupy\systems\symbolic.py", line 161, in update_state_equation_function
    if not self.dim_state or self.state_equation == empty_array():
  File "C:\Users\nicol\anaconda3\envs\tesi3\lib\site-packages\sympy\tensor\array\ndim_array.py", line 496, in __eq__
    return list(self) == list(other)
  File "C:\Users\nicol\anaconda3\envs\tesi3\lib\site-packages\sympy\tensor\array\ndim_array.py", line 461, in iterator
    yield self[()]
  File "C:\Users\nicol\anaconda3\envs\tesi3\lib\site-packages\sympy\tensor\array\dense_ndim_array.py", line 61, in __getitem__
    index = self._parse_index(index)
  File "C:\Users\nicol\anaconda3\envs\tesi3\lib\site-packages\sympy\tensor\array\ndim_array.py", line 78, in _parse_index
    raise ValueError("Index not valide with an empty array")
ValueError: Index not valide with an empty array

Thanks in advance for the help.

**Comment by sixpearls** [comment]
Hi @narr95, I do not currently support SymPy 1.5. I know Sympy 1.0 works, see the instructions in this [issue comment](https://github.com/simupy/simupy/issues/13#issuecomment-569407098).

**Comment by narr95** [comment]
@sixpearls thank you, now I can run the example.
