### ISSUE TITLE
examples not working?

### ISSUE THREAD

**Issue by kittypaw** [simupy/simupy#5]
Hi,
I downloaded this project and imported it into Pycharm. I tried to run these examples but nearly no script works properly. 
Here are the error messages of each script in the examples package:

bouncing_ball.py
Traceback (most recent call last):
  File "F:/PythonProject/simupy-master/examples/bouncing_ball.py", line 44, in <module>
    25, integrator_options=int_opts, event_find_options=find_opts
  File "F:\PythonProject\simupy-master\simupy\block_diagram.py", line 743, in simulate
    state_values
  File "F:\PythonProject\simupy-master\simupy\utils\__init__.py", line 24, in callable_from_trajectory
    x=[curves[:, i] for i in range(curves.shape[1])], u=t, s=0)
  File "E:\Program Files\Python37\lib\site-packages\scipy\interpolate\fitpack.py", line 157, in splprep
    quiet)
  File "E:\Program Files\Python37\lib\site-packages\scipy\interpolate\_fitpack_impl.py", line 280, in splprep
    task, ipar, s, t, nest, wrk, iwrk, per)
ValueError: Invalid inputs.

linearcontrol_nonlinearsys.py
Traceback (most recent call last):
  File "F:/PythonProject/simupy-master/examples/linearcontrol_nonlinearsys.py", line 33, in <module>
    Q = np.matlib.eye(3)
AttributeError: module 'numpy' has no attribute 'matlib'

riccati_system.py
Traceback (most recent call last):
  File "F:/PythonProject/simupy-master/examples/riccati_system.py", line 120, in <module>
    control_res = control_BD.simulate(tF)
  File "F:\PythonProject\simupy-master\simupy\block_diagram.py", line 551, in simulate
    x0 = self.initial_condition
  File "F:\PythonProject\simupy-master\simupy\block_diagram.py", line 121, in initial_condition
    x0[state_start:state_end] = sys.initial_condition
ValueError: could not broadcast input array from shape (2,1) into shape (2)

vanderpol.py
Traceback (most recent call last):
  File "F:/PythonProject/simupy-master/examples/vanderpol.py", line 29, in <module>
    res = BD.simulate(30)
  File "F:\PythonProject\simupy-master\simupy\block_diagram.py", line 560, in simulate
    y0 = self.output_equation_function(t0, x0, update_memoryless_event=True)
  File "F:\PythonProject\simupy-master\simupy\block_diagram.py", line 283, in output_equation_function
    sys.output_equation_function(t, state_values).reshape(-1)
  File "F:\PythonProject\simupy-master\simupy\utils\symbolic.py", line 68, in lambda_function_with_vector_args
    return np.array(f(*new_func_args))
  File "<lambdifygenerated-5>", line 2, in _lambdifygenerated
NameError: name 'atan2' is not defined

discrete_lti.py
This script runs successfully however with a runtime warning: 
MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot(n+m, 1, 1)

simple_saturation.py
This script finished with exit code 0, but has just a blank figure window flash back and no simulation result.

Here are the version information of my python and some dependent packages:
Python 3.7
numpy 1.16.4
scipy 1.3.0
sympy 1.4

**Comment by sixpearls** [comment]
Thank you for bringing this to my attention. This is currently between releases and the example code is a bit stale. I will work on updating them. Until I make the fixes, you can run the examples using version 1.0 of SimuPy.

**Comment by kittypaw** [comment]
There are still problems using release version 1.0 of SimuPy. 
The riccati_system.py seem to work now. 
The linearcontrol_nonlinearsys.py & vanderpol.py  have the same error messages.
The bouncing_ball.py & simple_saturation.py both have blank figure window flash back and no simulation results.
The discrete_lti.py still has the same runtime warnings.

I guess there is some conflict with the latest dependent packages?
